#ifndef __TASK_MANAGER_CFG_H
#define __TASK_MANAGER_CFG_H

#define POLL_SCHEDULER 1
#define PREEMPTIVE_SCHDULER 2

#define TASKSYS_HEAP_SPACE 1024 * 10 //10k memory space

#define TASK_SCHEDULER_TYPE PREEMPTIVE_SCHDULER
#if (TASK_SCHEDULER_TYPE == PREEMPTIVE_SCHDULER)

#define MSP_MEM_SPACE_SIZE TASKSYS_HEAP_SPACE //for 10k memory space
#define IDLE_TASK_STK_SZIE 128
#endif

#endif